--------------------------------------------------------
--  Constraints for Table TRVL_SP
--------------------------------------------------------

  ALTER TABLE "TRVL_SP" MODIFY ("TRVL_CD" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" MODIFY ("RAGION_CD" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" MODIFY ("TRSP_CLA" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" MODIFY ("TRVL_NM" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" MODIFY ("TRVL_X" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" MODIFY ("TRVL_Y" NOT NULL ENABLE);
  ALTER TABLE "TRVL_SP" ADD CONSTRAINT "TRVL_SP_PK" PRIMARY KEY ("TRVL_CD")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLASS_CD
--------------------------------------------------------

  ALTER TABLE "CLASS_CD" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "CLASS_CD" MODIFY ("CODE_NM" NOT NULL ENABLE);
  ALTER TABLE "CLASS_CD" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_CD" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS_CD" ADD CONSTRAINT "CLASS_CD_PK" PRIMARY KEY ("CODE_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRVL_LST
--------------------------------------------------------

  ALTER TABLE "TRVL_LST" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("TRVL_STD" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("TRVL_LSD" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("TRAVEL_DAYS" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" MODIFY ("RAGION_NM" NOT NULL ENABLE);
  ALTER TABLE "TRVL_LST" ADD CONSTRAINT "TRVL_LST_PK" PRIMARY KEY ("PLAN_ID", "MANAGEMENT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table GB
--------------------------------------------------------

  ALTER TABLE "GB" MODIFY ("GB_ID" NOT NULL ENABLE);
  ALTER TABLE "GB" MODIFY ("GOOD" NOT NULL ENABLE);
  ALTER TABLE "GB" MODIFY ("BAD" NOT NULL ENABLE);
  ALTER TABLE "GB" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "GB" ADD CONSTRAINT "PK_GB_ID" PRIMARY KEY ("GB_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "GB" MODIFY ("BBS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MANAGEMENT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBERTB_MEMBER_ID_UK" UNIQUE ("MEMBER_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBERTB_NICKNAME_UK" UNIQUE ("NICKNAME")
  USING INDEX  ENABLE;
  ALTER TABLE "MEMBER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRVL_PL
--------------------------------------------------------

  ALTER TABLE "TRVL_PL" MODIFY ("PM_ID" NOT NULL ENABLE);
  ALTER TABLE "TRVL_PL" MODIFY ("TRVL_CD" NOT NULL ENABLE);
  ALTER TABLE "TRVL_PL" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRVL_PL" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TRVL_PL" MODIFY ("TRVL_DAY" NOT NULL ENABLE);
  ALTER TABLE "TRVL_PL" ADD CONSTRAINT "TRVL_PL_PK" PRIMARY KEY ("PM_ID", "PLAN_ID", "MANAGEMENT_ID", "TRVL_CD")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table UPLOAD_FL
--------------------------------------------------------

  ALTER TABLE "UPLOAD_FL" MODIFY ("UPLOADFILE_ID" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("BBS_ID" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("UPLOAD_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("FSIZE" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("FTYPE" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "UPLOAD_FL" ADD CONSTRAINT "UPLOAD_FL_PK" PRIMARY KEY ("UPLOADFILE_ID", "BBS_ID", "MANAGEMENT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BBS
--------------------------------------------------------

  ALTER TABLE "BBS" MODIFY ("BBS_ID" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("BCONTENT" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("GOOD" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("BAD" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "BBS" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "BBS" ADD CONSTRAINT "BBS_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX (CREATE INDEX "BBS_PK_IDX" ON "BBS" ("BBS_ID") 
  )  ENABLE;
--------------------------------------------------------
--  Constraints for Table RBBS
--------------------------------------------------------

  ALTER TABLE "RBBS" MODIFY ("RBBS_ID" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("BBS_ID" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "RBBS" MODIFY ("BCONTENT" NOT NULL ENABLE);
  ALTER TABLE "RBBS" ADD CONSTRAINT "RBBS_PK" PRIMARY KEY ("RBBS_ID", "BBS_ID", "MANAGEMENT_ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table AREA_CD
--------------------------------------------------------

  ALTER TABLE "AREA_CD" MODIFY ("RAGION_CD" NOT NULL ENABLE);
  ALTER TABLE "AREA_CD" MODIFY ("RAGION_NM" NOT NULL ENABLE);
  ALTER TABLE "AREA_CD" MODIFY ("UDATE" NOT NULL ENABLE);
  ALTER TABLE "AREA_CD" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "AREA_CD" ADD CONSTRAINT "AREA_CD_PK" PRIMARY KEY ("RAGION_CD")
  USING INDEX  ENABLE;
