DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    MANAGEMENT_ID    NUMBER(10) NOT NULL,
    MEMBER_ID    VARCHAR2(12) NOT NULL,
    PW    VARCHAR2(20) NOT NULL,
    TEL    VARCHAR2(11),
    NICKNAME    VARCHAR2(36) NOT NULL,
    GENDER    VARCHAR2(3),
    ADDRESS    VARCHAR2(120),
    UDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CODE_ID    VARCHAR2(6) NOT NULL
);

COMMENT ON COLUMN MEMBER.MANAGEMENT_ID IS '내부관리용아이디';

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';

COMMENT ON COLUMN MEMBER.PW IS '비밀번호';

COMMENT ON COLUMN MEMBER.TEL IS '전화번호';

COMMENT ON COLUMN MEMBER.NICKNAME IS '별칭';

COMMENT ON COLUMN MEMBER.GENDER IS '성별';

COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';

COMMENT ON COLUMN MEMBER.UDATE IS '변경일';

COMMENT ON COLUMN MEMBER.CDATE IS '작성일';

COMMENT ON COLUMN MEMBER.CODE_ID IS '회원구분코드';

COMMENT ON TABLE MEMBER IS '회원';

CREATE UNIQUE INDEX MEMBER_PK ON MEMBER
( MANAGEMENT_ID );

ALTER TABLE MEMBER
 ADD CONSTRAINT MEMBER_PK PRIMARY KEY ( MANAGEMENT_ID )
 USING INDEX MEMBER_PK;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBERTB_MEMBER_ID_UK UNIQUE (MEMBER_ID);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBERTB_NICKNAME_UK UNIQUE (NICKNAME);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBERTB_MEMBER_ID_UK UNIQUE (MEMBER_ID);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBERTB_CODE_ID_FK
FOREIGN KEY (CODE_ID)
REFERENCES CLASS_CD(CODE_ID);

ALTER TABLE MEMBER
ADD BIRTHDAY DATE;

ALTER TABLE MEMBER
MODIFY BIRTHDAY DATE NOT NULL;

ALTER TABLE MEMBER
ADD EMAIL VARCHAR2(100);

ALTER TABLE MEMBER
MODIFY EMAIL VARCHAR2(100) NOT NULL;