DROP TABLE TRVL_SP;

CREATE TABLE TRVL_SP
(
    TRVL_CD    NUMBER(10) NOT NULL,
    RAGION_CD    VARCHAR2(6) NOT NULL,
    TRSP_CLA    VARCHAR2(6) NOT NULL,
    TRVL_NM    VARCHAR2(243) NOT NULL,
    TRVL_ADDR    VARCHAR2(210),
    IMG    VARCHAR2(200),
    IMG2    VARCHAR2(200),
    TRVL_X   NUMBER(20,15) NOT NULL,
    TRVL_Y    NUMBER(20,15) NOT NULL,
    TRVL_ZIPCD    VARCHAR2(10)
);

COMMENT ON COLUMN TRVL_SP.TRVL_CD IS '여행지코드';

COMMENT ON COLUMN TRVL_SP.RAGION_CD IS '지역코드';

COMMENT ON COLUMN TRVL_SP.TRSP_CLA IS '여행지분류';

COMMENT ON COLUMN TRVL_SP.TRVL_NM IS '여행지명';

COMMENT ON COLUMN TRVL_SP.TRVL_ADDR IS '여행지주소';

COMMENT ON COLUMN TRVL_SP.IMG IS '여행지사진1';

COMMENT ON COLUMN TRVL_SP.IMG2 IS '여행지사진2';

COMMENT ON COLUMN TRVL_SP.TRVL_X IS '여행지X좌표';

COMMENT ON COLUMN TRVL_SP.TRVL_Y IS '여행지Y좌표';

COMMENT ON COLUMN TRVL_SP.TRVL_ZIPCD IS '여행지 우편번호';

COMMENT ON TABLE TRVL_SP IS '여행지';

CREATE UNIQUE INDEX TRVL_SP_PK ON TRVL_SP
( TRVL_CD );

ALTER TABLE TRVL_SP
 ADD CONSTRAINT TRVL_SP_PK PRIMARY KEY ( TRVL_CD )
 USING INDEX TRVL_SP_PK;