DROP TABLE TRVL_LST;

CREATE TABLE TRVL_LST
(
    PLAN_ID    NUMBER(20) NOT NULL,
    MANAGEMENT_ID    NUMBER(10) NOT NULL,
    TRVL_NM    VARCHAR2(150),
    TRVL_STD    VARCHAR2(10) NOT NULL,
    TRVL_LSD    VARCHAR2(10) NOT NULL,
    TRAVEL_DAYS    VARCHAR2(1) NOT NULL,
    CDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL,
    RAGION_NM    VARCHAR2(21) NOT NULL
);

COMMENT ON COLUMN TRVL_LST.PLAN_ID IS '여행일정아이디';

COMMENT ON COLUMN TRVL_LST.MANAGEMENT_ID IS '내부관리용아이디';

COMMENT ON COLUMN TRVL_LST.TRVL_NM IS '여행이름';

COMMENT ON COLUMN TRVL_LST.TRVL_STD IS '여행시작일';

COMMENT ON COLUMN TRVL_LST.TRVL_LSD IS '여행종료일';

COMMENT ON COLUMN TRVL_LST.TRAVEL_DAYS IS '여행일수';

COMMENT ON COLUMN TRVL_LST.CDATE IS '작성일';

COMMENT ON COLUMN TRVL_LST.UDATE IS '수정일';

COMMENT ON COLUMN TRVL_LST.RAGION_NM IS '지역명';

COMMENT ON TABLE TRVL_LST IS '회원여행일정목록';

CREATE UNIQUE INDEX TRVL_LST_PK ON TRVL_LST
( PLAN_ID,MANAGEMENT_ID );

ALTER TABLE TRVL_LST
 ADD CONSTRAINT TRVL_LST_PK PRIMARY KEY ( PLAN_ID,MANAGEMENT_ID )
 USING INDEX TRVL_LST_PK;

ALTER TABLE TRVL_LST
ADD CONSTRAINT TRVL_LSTTB_MANAGEMENT_ID_FK
FOREIGN KEY (MANAGEMENT_ID)
REFERENCES MEMBER(MANAGEMENT_ID);

ALTER TABLE TRVL_LST
MODIFY TRVL_STD DATE;

ALTER TABLE TRVL_LST
MODIFY TRVL_LSD DATE;