DROP TABLE UPLOAD_FL;

CREATE TABLE UPLOAD_FL
(
    UPLOADFILE_ID    NUMBER(10) NOT NULL,
    BBS_ID    NUMBER(10) NOT NULL,
    MANAGEMENT_ID    NUMBER(10) NOT NULL,
    UPLOAD_FILENAME    VARCHAR2(50) NOT NULL,
    FSIZE    VARCHAR2(10) NOT NULL,
    FTYPE    VARCHAR2(6) NOT NULL,
    CDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UDATE    TIMESTAMP DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN UPLOAD_FL.UPLOADFILE_ID IS '파일아이디';

COMMENT ON COLUMN UPLOAD_FL.BBS_ID IS '게시글번호';

COMMENT ON COLUMN UPLOAD_FL.MANAGEMENT_ID IS '내부관리용아이디';

COMMENT ON COLUMN UPLOAD_FL.UPLOAD_FILENAME IS '업로드파일명';

COMMENT ON COLUMN UPLOAD_FL.FSIZE IS '파일크기';

COMMENT ON COLUMN UPLOAD_FL.FTYPE IS '파일유형';

COMMENT ON COLUMN UPLOAD_FL.CDATE IS '작성일';

COMMENT ON COLUMN UPLOAD_FL.UDATE IS '수정일';

COMMENT ON TABLE UPLOAD_FL IS '업로드파일';

CREATE UNIQUE INDEX UPLOAD_FL_PK ON UPLOAD_FL
( UPLOADFILE_ID,BBS_ID,MANAGEMENT_ID );

ALTER TABLE UPLOAD_FL
 ADD CONSTRAINT UPLOAD_FL_PK PRIMARY KEY ( UPLOADFILE_ID,BBS_ID,MANAGEMENT_ID )
 USING INDEX UPLOAD_FL_PK;

ALTER TABLE UPLOAD_FL
ADD CONSTRAINT UPLOAD_FLTB_BBS_ID_FK
FOREIGN KEY (BBS_ID)
REFERENCES BBS(BBS_ID);